// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqrfxeagkawxtsljqtpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxcmZ4ZWFna2F3eHRzbGpxdHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzExNjEsImV4cCI6MjA3Mzk0NzE2MX0.AJctr9OgGl2I3s89_06ccawRcyiMokhPCFcFJqA6e9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});